import { writeFileSync, mkdirSync } from 'node:fs';
import * as path from 'node:path';
import { fileURLToPath } from 'node:url';
import { sqlite } from 'src/db/index.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const EXCLUDED_TABLES = new Set([
  'kysely_migration',
  'kysely_migration_lock',
  'sqlite_sequence',
  'sqlite_stat1',
  'sqlite_stat4',
]);

type Column = {
  cid: number;
  name: string;
  type: string;
  notnull: 0 | 1;
  dflt_value: string | null;
  pk: number;
};

type IndexInfo = {
  seq: number;
  name: string;
  unique: 0 | 1;
  origin: 'c' | 'u' | 'pk';
  partial: 0 | 1;
};

type IndexColumn = { seqno: number; cid: number; name: string };

type FkInfo = {
  id: number;
  seq: number;
  table: string;
  from: string;
  to: string;
  on_update: string;
  on_delete: string;
  match: string;
};

const quoteIdent = (name: string) => `"${name.replace(/"/g, '""')}"`;

function listTables(): string[] {
  const rows = sqlite
    .prepare(
      "SELECT name FROM sqlite_master WHERE type = 'table' ORDER BY name"
    )
    .all() as { name: string }[];
  return rows
    .map(r => r.name)
    .filter(n => !EXCLUDED_TABLES.has(n) && !n.startsWith('sqlite_'));
}

const tableInfo = (t: string) =>
  sqlite.prepare(`PRAGMA table_info(${quoteIdent(t)})`).all() as Column[];
const indexList = (t: string) =>
  sqlite.prepare(`PRAGMA index_list(${quoteIdent(t)})`).all() as IndexInfo[];
const indexInfo = (i: string) =>
  sqlite.prepare(`PRAGMA index_info(${quoteIdent(i)})`).all() as IndexColumn[];
const foreignKeys = (t: string) =>
  sqlite.prepare(`PRAGMA foreign_key_list(${quoteIdent(t)})`).all() as FkInfo[];

function typeFlag(declared: string): string {
  const t = declared.toUpperCase();
  if (t === 'TEXT_DATETIME') return 'Timestamp';
  if (t === 'INTEGER_BOOLEAN') return 'Bool';
  if (t.includes('INT')) return 'Integer';
  if (t.includes('TEXT') || t.includes('CHAR') || t.includes('CLOB'))
    return 'Text';
  if (t.includes('REAL') || t.includes('FLOA') || t.includes('DOUB'))
    return 'Real';
  if (t.includes('BLOB') || t === '') return 'Blob';
  return 'Numeric';
}

function tsStringLiteral(s: string): string {
  const hasSingle = s.includes("'");
  const hasDouble = s.includes('"');
  if (hasSingle && !hasDouble) return `"${s}"`;
  if (hasDouble && !hasSingle) return `'${s}'`;
  return `'${s.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
}

const ON_DELETE_FLAG: Record<string, string> = {
  CASCADE: 'ON_DELETE.CASCADE',
  'SET NULL': 'ON_DELETE.SET_NULL',
  'SET DEFAULT': 'ON_DELETE.SET_DEFAULT',
  RESTRICT: 'ON_DELETE.RESTRICT',
  'NO ACTION': 'ON_DELETE.NO_ACTION',
};

const COMMON_FIELDS = ['id', 'createdAt', 'updatedAt'];

function main(): void {
  const tables = listTables();

  const tableColumns = new Map<string, Column[]>();
  const tableIndexes = new Map<string, IndexInfo[]>();
  const tableIndexCols = new Map<string, IndexColumn[]>();
  const tableFks = new Map<string, FkInfo[]>();
  const usedFlags = new Set<string>();

  for (const t of tables) {
    const cols = tableInfo(t);
    tableColumns.set(t, cols);
    cols.forEach(c => usedFlags.add(typeFlag(c.type)));

    const idxs = indexList(t).filter(i => i.origin !== 'pk');
    tableIndexes.set(t, idxs);
    for (const idx of idxs) tableIndexCols.set(idx.name, indexInfo(idx.name));

    tableFks.set(t, foreignKeys(t));
  }

  const lines: string[] = [
    '// Auto-generated by scripts/db/generate-schema-review.ts',
    '// Do not edit manually — re-run to regenerate.',
    '/* eslint-disable */',
    'export {}',
    '',
    '// ── Column type flags ──',
  ];

  const knownFlags = [
    'Integer',
    'Text',
    'Real',
    'Blob',
    'Numeric',
    'Timestamp',
    'Bool',
  ];
  for (const f of knownFlags)
    if (usedFlags.has(f)) lines.push(`type ${f} = '${f}'`);

  lines.push('');
  lines.push('// ── Column modifier flags ──');
  lines.push('type PK = { _pk: true }');
  lines.push('type DEFAULT<V> = { _default: V }');
  lines.push('');
  lines.push('// ── OnDelete flags ──');
  lines.push('namespace ON_DELETE {');
  lines.push("  export type CASCADE = { _onDelete: 'cascade' }");
  lines.push("  export type SET_NULL = { _onDelete: 'set null' }");
  lines.push("  export type SET_DEFAULT = { _onDelete: 'set default' }");
  lines.push("  export type RESTRICT = { _onDelete: 'restrict' }");
  lines.push("  export type NO_ACTION = { _onDelete: 'no action' }");
  lines.push('}');
  lines.push('');
  lines.push('// ── Index flags ──');
  lines.push('type UNIQUE = { _unique: true }');
  lines.push('type PARTIAL_IDX = { _partial: true }');
  lines.push('');

  for (const tableName of tables) {
    const cols = tableColumns.get(tableName) ?? [];
    const idxs = tableIndexes.get(tableName) ?? [];
    const fks = tableFks.get(tableName) ?? [];

    const fkByCol = new Map<string, FkInfo>();
    for (const fk of fks) {
      if (!fkByCol.has(fk.from)) fkByCol.set(fk.from, fk);
    }

    const baseCols: Column[] = [];
    const fieldCols: Column[] = [];
    const relCols: Column[] = [];
    for (const c of cols) {
      if (COMMON_FIELDS.includes(c.name)) baseCols.push(c);
      else if (fkByCol.has(c.name)) relCols.push(c);
      else fieldCols.push(c);
    }
    baseCols.sort(
      (a, b) => COMMON_FIELDS.indexOf(a.name) - COMMON_FIELDS.indexOf(b.name)
    );
    const nullableThenAlpha = (a: Column, b: Column) => {
      const aN = a.notnull ? 0 : 1;
      const bN = b.notnull ? 0 : 1;
      if (aN !== bN) return aN - bN;
      return a.name.localeCompare(b.name);
    };
    fieldCols.sort(nullableThenAlpha);
    relCols.sort(nullableThenAlpha);

    lines.push(`type ${tableName} = {`);

    const emit = (c: Column) => {
      const flags: string[] = [typeFlag(c.type)];
      if (c.pk) flags.push('PK');
      if (c.dflt_value !== null && c.dflt_value !== 'NULL') {
        const raw = c.dflt_value;
        if (/^-?\d+(\.\d+)?$/.test(raw)) {
          flags.push(`DEFAULT<${raw}>`);
        } else {
          const inner = /^'.*'$/.test(raw) ? raw.slice(1, -1) : raw;
          flags.push(`DEFAULT<${tsStringLiteral(inner)}>`);
        }
      }
      const fk = fkByCol.get(c.name);
      if (fk && !EXCLUDED_TABLES.has(fk.table)) {
        flags.push(
          ON_DELETE_FLAG[fk.on_delete.toUpperCase()] ?? 'ON_DELETE.NO_ACTION'
        );
        flags.push(`${fk.table}['${fk.to}']`);
      }
      const propName = c.notnull ? c.name : `${c.name}?`;
      lines.push(`  ${propName}: ${flags.join(' | ')}`);
    };

    if (baseCols.length) {
      lines.push('  // ── base ──');
      baseCols.forEach(emit);
    }
    if (fieldCols.length) {
      lines.push('  // ── fields ──');
      fieldCols.forEach(emit);
    }
    if (relCols.length) {
      lines.push('  // ── relations ──');
      relCols.forEach(emit);
    }

    if (idxs.length) {
      lines.push('  // ── indexes ──');
      lines.push('  _indexes: {');
      const prefix = `${tableName}_`;
      for (const idx of idxs) {
        const colNames = (tableIndexCols.get(idx.name) ?? []).map(c => c.name);
        const colRefs = colNames.map(n => `${tableName}['${n}']`).join(', ');
        let baseName = idx.name;
        if (baseName.startsWith('sqlite_autoindex_')) {
          baseName = colNames.join('_');
        } else {
          if (baseName.startsWith(prefix))
            baseName = baseName.slice(prefix.length);
          baseName = baseName.replace(/_(idx|key)$/, '');
        }
        const allFlags: string[] = [`[${colRefs}]`];
        if (idx.unique) allFlags.push('UNIQUE');
        if (idx.partial) allFlags.push('PARTIAL_IDX');
        lines.push(`    ${baseName}: ${allFlags.join(' | ')}`);
      }
      lines.push('  }');
    }

    lines.push('}');
    lines.push('');
  }

  const outDir = path.resolve(__dirname, '../../__generated__');
  mkdirSync(outDir, { recursive: true });
  const outPath = path.join(outDir, 'schema-review.ts');
  writeFileSync(outPath, lines.join('\n'));
  console.info(`Written ${path.relative(process.cwd(), outPath)}`);
}

try {
  main();
} finally {
  sqlite.close();
}
