import type { Job, Tab } from 'src/tui/types.js';

export const TABS: { key: Tab; label: string; count: number }[] = [
  { key: 'TODAS', label: 'TODAS', count: 516 },
  { key: 'EVALUADA', label: 'EVALUADA', count: 154 },
  { key: 'APLICADO', label: 'APLICADO', count: 66 },
  { key: 'ENTREVISTA', label: 'ENTREVISTA', count: 10 },
  { key: 'TOP', label: 'TOP ≥4', count: 142 },
  { key: 'NO APLICAR', label: 'NO APLICAR', count: 219 },
];

export const JOBS: Job[] = [
  {
    score: 4.5,
    company: 'Datadog',
    title: 'Staff AI Engineer, MCP Services',
    status: 'Evaluada',
    salary: null,
  },
  {
    score: 4.3,
    company: 'Dialpad',
    title: 'Sr. AI Solutions Architect',
    status: 'Evaluada',
    salary: null,
  },
  {
    score: 4.2,
    company: 'Mirakl',
    title: 'Senior AI Product Manager (Nexus Shopping Agent)',
    status: 'Evaluada',
    salary: null,
  },
  {
    score: 4.2,
    company: 'dsm-firmenich',
    title: 'Senior Director, Data & AI Product Management Lead',
    status: 'Evaluada',
    salary: null,
  },
  {
    score: 4.2,
    company: 'Forethought',
    title: 'AI Solutions Architect / AI Integration Consultant',
    status: 'Evaluada',
    salary: 'Not disclo…',
  },
  {
    score: 4.2,
    company: 'Langfuse',
    title: 'Founding DevRel Engineer',
    status: 'Evaluada',
    salary: null,
  },
  {
    score: 4.2,
    company: 'Dow Jones',
    title: 'Principal PM AI Platform',
    status: 'Evaluada',
    salary: null,
  },
  {
    score: 4.2,
    company: 'Make',
    title: 'Senior TypeScript AI Engineer',
    status: 'Evaluada',
    salary: 'RSU grants…',
  },
  {
    score: 4.2,
    company: 'Hopper',
    title: 'Senior PM, Commerce – AI & Platform (Spain)',
    status: 'Evaluada',
    salary: null,
  },
  {
    score: 4.1,
    company: 'OLX',
    title: 'Principal Product Manager – GenAI',
    status: 'Evaluada',
    salary: 'Salary + a…',
  },
  {
    score: 4.1,
    company: 'Ometria',
    title: 'AI Evangelist',
    status: 'Evaluada',
    salary: null,
  },
  {
    score: 4.1,
    company: 'Poolside',
    title: 'Solutions Engineer Pre-Sales EMEA',
    status: 'Evaluada',
    salary: 'Not listed…',
  },
  {
    score: 4.1,
    company: 'Vapi',
    title: 'Voice Architect',
    status: 'Evaluada',
    salary: null,
  },
  {
    score: 4.1,
    company: 'n8n',
    title: 'Head of AI & Automation',
    status: 'Evaluada',
    salary: null,
  },
  {
    score: 4.1,
    company: '??? (via Blockcha…',
    title: 'AI Growth Engineer & Martech',
    status: 'Evaluada',
    salary: '$100K-$150…',
  },
  {
    score: 4.1,
    company: 'Simetrik',
    title: 'AI Engineer',
    status: 'Evaluada',
    salary: null,
  },
  {
    score: 4.1,
    company: 'Trace3',
    title: 'Solutions Architect, AI',
    status: 'Evaluada',
    salary: 'Est. $150,…',
  },
  {
    score: 4.0,
    company: 'Glean',
    title: 'Founding Forward Deployed Engineer',
    status: 'Evaluada',
    salary: null,
  },
  {
    score: 4.0,
    company: 'Dataiku',
    title: 'Technical Product Manager – xOps',
    status: 'Evaluada',
    salary: null,
  },
  {
    score: 4.0,
    company: 'LangChain',
    title: 'SA, Applied AI',
    status: 'Evaluada',
    salary: null,
  },
  {
    score: 4.0,
    company: 'OpenAI',
    title: 'FDE Munich',
    status: 'Evaluada',
    salary: null,
  },
  {
    score: 4.0,
    company: 'Checkmate',
    title: 'TPM Voice AI (Senior/Principal)',
    status: 'Evaluada',
    salary: null,
  },
];
