# Zsh completion for jobfinder. Generated by "jobfinder completion".
# Install: source <(jobfinder completion)

# Bootstrap zsh's completion system if the caller hasn't already.
if ! (( $+functions[compdef] )); then
  autoload -Uz compinit && compinit
fi

_jobfinder_pipeline_sourcing() {
  _arguments -s -S \
    '--all[all]' \
    '--include-failed[include-failed]' \
    '--job-source-id[job-source-id]:job-source-id:' \
    '--start[start]'
}

_jobfinder_pipeline_listing() {
  _arguments -s -S \
    '--all[all]' \
    '--include-failed[include-failed]' \
    '--job-source-id[job-source-id]:job-source-id:' \
    '--start[start]'
}

_jobfinder_pipeline_scripting() {
  _arguments -s -S \
    '--all[all]' \
    '--include-failed[include-failed]' \
    '--job-list-source-id[job-list-source-id]:job-list-source-id:' \
    '--start[start]'
}

_jobfinder_pipeline_run_scripts() {
  _arguments -s -S \
    '(-d --division)'{-d,--division}'[division]:division:' \
    '(-l --location)'{-l,--location}'[location]:location:' \
    '--all[all]' \
    '--include-failed[include-failed]' \
    '--job-list-source-id[job-list-source-id]:job-list-source-id:' \
    '--start[start]'
}

_jobfinder_pipeline_viewing() {
  _arguments -s -S \
    '--all[all]' \
    '--include-failed[include-failed]' \
    '--job-post-id[job-post-id]:job-post-id:' \
    '--start[start]'
}

_jobfinder_pipeline_evaluate() {
  _arguments -s -S \
    '--all[all]' \
    '--include-failed[include-failed]' \
    '--job-post-id[job-post-id]:job-post-id:' \
    '--start[start]'
}

_jobfinder_pipeline() {
  local state line
  typeset -A opt_args

  _arguments -C \
    '1:subcommand:(seeding approve-seeds sourcing listing scripting run-scripts viewing evaluate)' \
    '*:: :->args'

  case $state in
    args)
      case $line[1] in
    seeding) _normal ;;
    approve-seeds) _normal ;;
    sourcing) _jobfinder_pipeline_sourcing ;;
    listing) _jobfinder_pipeline_listing ;;
    scripting) _jobfinder_pipeline_scripting ;;
    run-scripts) _jobfinder_pipeline_run_scripts ;;
    viewing) _jobfinder_pipeline_viewing ;;
    evaluate) _jobfinder_pipeline_evaluate ;;
      esac
      ;;
  esac
}

_jobfinder_reset() {
  _arguments -s -S \
    '1:stage:(sourcing listing scripting run-scripts viewing evaluate)' \
    '--all[all]' \
    '--no-result[no-result]' \
    '--failed[failed]'
}

_jobfinder_start_pipeline() {
  _arguments -s -S \
    '--include-failed[include-failed]'
}

_jobfinder_export_jobs() {
  _arguments -s -S \
    '1::output:' \
    '(-s --sort)'{-s,--sort}'[sort]:sort:(all interest skill location excl. interest excl. location)'
}

_jobfinder_export() {
  local state line
  typeset -A opt_args

  _arguments -C \
    '1:subcommand:(jobs)' \
    '*:: :->args'

  case $state in
    args)
      case $line[1] in
    jobs) _jobfinder_export_jobs ;;
      esac
      ;;
  esac
}

_jobfinder_track() {
  _arguments -s -S \
    '1:url:'
}

_jobfinder_tui() {
  _arguments -s -S \
    '--tab[tab]:tab:(jobs sources)' \
    '--sort[sort]:sort:(all interest skill location excl. interest excl. location)' \
    '--sources-sort[sources-sort]:sources-sort:(interest posts name)' \
    '--non-interactive[non-interactive]' \
    '--harness[harness]' \
    '--harness-port[harness-port]:harness-port:'
}

_jobfinder_help_menu_dump() {
  _arguments -s -S \
    '--pretty[pretty]' \
    '--no-pretty[no-pretty]'
}

_jobfinder() {
  local state line
  typeset -A opt_args

  _arguments -C \
    '1:subcommand:(init pipeline reset start-pipeline export track tui completion help-menu-dump)' \
    '*:: :->args'

  case $state in
    args)
      case $line[1] in
    init) _normal ;;
    pipeline) _jobfinder_pipeline ;;
    reset) _jobfinder_reset ;;
    start-pipeline) _jobfinder_start_pipeline ;;
    export) _jobfinder_export ;;
    track) _jobfinder_track ;;
    tui) _jobfinder_tui ;;
    completion) _normal ;;
    help-menu-dump) _jobfinder_help_menu_dump ;;
      esac
      ;;
  esac
}

compdef _jobfinder jobfinder ./bin/jobfinder

[34m# wrote /Users/yuli/lab/job-finder/.claude/worktrees/reset-command/__generated__/cli/_completion.zsh[39m
