# Zsh completion for cli. Generated by "cli completion zsh".
# Install: source <(./src/cli/bin/cli completion zsh)

_cli_scrape() {
  _arguments -s -S \
    '(-s --site)'{-s,--site}'[site]:site:(linkedin indeed zip_recruiter glassdoor google bayt naukri bdjobs)' \
    '(-q --search)'{-q,--search}'[search]:search:' \
    '--google-search[google-search]:google-search:' \
    '(-l --location)'{-l,--location}'[location]:location:' \
    '(-d --distance)'{-d,--distance}'[distance]:distance:' \
    '--remote[remote]' \
    '--job-type[job-type]:job-type:(fulltime parttime contract temporary internship perdiem nights other summer volunteer)' \
    '--easy-apply[easy-apply]' \
    '(-n --results)'{-n,--results}'[results]:results:' \
    '--country[country]:country:' \
    '--proxy[proxy]:proxy:' \
    '--ca-cert[ca-cert]:ca-cert:' \
    '--description-format[description-format]:description-format:(markdown html)' \
    '--linkedin-fetch-description[linkedin-fetch-description]' \
    '--linkedin-company-id[linkedin-company-id]:linkedin-company-id:' \
    '--offset[offset]:offset:' \
    '--hours-old[hours-old]:hours-old:' \
    '--enforce-annual-salary[enforce-annual-salary]' \
    '--verbose[verbose]:verbose:' \
    '--user-agent[user-agent]:user-agent:' \
    '(-f --format)'{-f,--format}'[format]:format:(json csv)' \
    '(-o --output)'{-o,--output}'[output]:output:'
}

_cli_completion() {
  local state line
  typeset -A opt_args

  _arguments -C \
    '1:subcommand:(zsh)' \
    '*:: :->args'

  case $state in
    args)
      case $line[1] in
    zsh) _normal ;;
      esac
      ;;
  esac
}

_cli() {
  local state line
  typeset -A opt_args

  _arguments -C \
    '1:subcommand:(scrape sites completion)' \
    '*:: :->args'

  case $state in
    args)
      case $line[1] in
    scrape) _cli_scrape ;;
    sites) _normal ;;
    completion) _cli_completion ;;
      esac
      ;;
  esac
}

compdef _cli cli ./src/cli/bin/cli
