/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely';
import type { Bool, Timestamp } from 'src/db/customTypes';

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export interface JobListSource {
  createdAt: Generated<Timestamp>;
  divisions: string | null;
  id: string;
  isActive: Generated<Bool>;
  locations: string | null;
  ofJobSourceId: string;
  parserScript: string | null;
  updatedAt: Generated<Timestamp>;
  url: string;
}

export interface JobPost {
  company: string | null;
  createdAt: Generated<Timestamp>;
  description: string | null;
  fillFormScript: string | null;
  id: string;
  isManuallyExcluded: Generated<Bool>;
  isRemote: Bool | null;
  jobType: string | null;
  location: string | null;
  manualExclusionReason: string | null;
  ofJobListSourceId: string | null;
  ofJobSourceId: string;
  postedAt: Timestamp | null;
  postedAtSource: string | null;
  salaryCurrency: string | null;
  salaryInterval: string | null;
  salaryMax: number | null;
  salaryMin: number | null;
  skillRequirements: string | null;
  summary: string | null;
  tags: string | null;
  title: string;
  updatedAt: Generated<Timestamp>;
  url: string;
}

export interface JobPostEval {
  createdAt: Generated<Timestamp>;
  id: string;
  interestScore: number | null;
  interestScoreReason: string | null;
  locationRelevancy: number | null;
  locationRelevancyReason: string | null;
  locationScore: number | null;
  locationScoreReason: string | null;
  ofJobPostId: string;
  skillScore: number | null;
  skillScoreBreakdown: string | null;
  skillScoreReason: string | null;
  titleRelavency: number | null;
  titleRelavencyReason: string | null;
  updatedAt: Generated<Timestamp>;
}

export interface JobSource {
  abortListingReason: string | null;
  createdAt: Generated<Timestamp>;
  id: string;
  interestScore: number | null;
  interestScoreReason: string | null;
  isActive: Generated<Bool>;
  name: string;
  summary: string | null;
  updatedAt: Generated<Timestamp>;
  url: string | null;
}

export interface LatestPipelineState {
  createdAt: string | null;
  id: string | null;
  ofJobListSourceId: string | null;
  ofJobPostId: string | null;
  ofJobSourceId: string | null;
  ofSourceSeedId: string | null;
  reason: string | null;
  state: string | null;
  task: string | null;
  updatedAt: string | null;
}

export interface PipelineState {
  createdAt: Generated<Timestamp>;
  id: string;
  ofJobListSourceId: string | null;
  ofJobPostId: string | null;
  ofJobSourceId: string | null;
  ofSourceSeedId: string | null;
  reason: string | null;
  state: string;
  task: string;
  updatedAt: Generated<Timestamp>;
}

export interface SourceSeed {
  createdAt: Generated<Timestamp>;
  id: string;
  name: string;
  title: string;
  updatedAt: Generated<Timestamp>;
  url: string;
}

export interface DB {
  JobListSource: JobListSource;
  JobPost: JobPost;
  JobPostEval: JobPostEval;
  JobSource: JobSource;
  LatestPipelineState: LatestPipelineState;
  PipelineState: PipelineState;
  SourceSeed: SourceSeed;
}
