import { writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { Command } from 'commander';

const CLI_NAME = 'cli';

type OptionLike = {
  long?: string;
  short?: string;
  argChoices?: string[];
  required?: boolean;
  optional?: boolean;
  _hidden?: boolean;
  description?: string;
};

type ArgumentLike = {
  _name: string;
  description: string;
  required: boolean;
  variadic: boolean;
  argChoices?: string[];
};

function getVisibleOptions(cmd: Command): OptionLike[] {
  return ([...cmd.options] as OptionLike[]).filter(o => {
    if (o._hidden) return false;
    const long = o.long?.replace(/^--/, '');
    return long !== 'help' && long !== 'version';
  });
}

function getRegisteredArguments(cmd: Command): ArgumentLike[] {
  return (cmd.registeredArguments ?? []) as unknown as ArgumentLike[];
}

function getVisibleSubcommands(cmd: Command): Command[] {
  return (cmd.commands as Command[]).filter(
    c => !(c as Command & { _hidden?: boolean })._hidden && c.name() !== 'help'
  );
}

function formatOptionSpec(option: OptionLike): string {
  const { short, long } = option;
  const desc = long?.replace(/^--/, '') ?? short?.replace(/^-/, '') ?? '';

  let valueSuffix = '';
  if (option.argChoices?.length) {
    valueSuffix = `:${desc}:(${option.argChoices.join(' ')})`;
  } else if (option.required) {
    valueSuffix = `:${desc}:`;
  } else if (option.optional) {
    valueSuffix = `::${desc}:`;
  }

  if (short && long) {
    return `'(${short} ${long})'{${short},${long}}'[${desc}]${valueSuffix}'`;
  }
  const flag = long ?? short!;
  return `'${flag}[${desc}]${valueSuffix}'`;
}

function formatArgumentSpec(arg: ArgumentLike, position: number): string {
  const colon = arg.required ? ':' : '::';
  const choices = arg.argChoices?.length ? `(${arg.argChoices.join(' ')})` : '';
  return `'${position}${colon}${arg._name}:${choices}'`;
}

function generateLeafHandler(cmd: Command, fnName: string): string {
  const opts = getVisibleOptions(cmd);
  const args = getRegisteredArguments(cmd);
  if (opts.length === 0 && args.length === 0) return '';

  const specs: string[] = [];
  args.forEach((arg, i) => specs.push(formatArgumentSpec(arg, i + 1)));
  opts.forEach(o => specs.push(formatOptionSpec(o)));

  const joined = specs.join(' \\\n    ');
  return `${fnName}() {
  _arguments -s -S \\
    ${joined}
}
`;
}

function generateBranchHandler(
  cmd: Command,
  fnName: string,
  leafFunctions: string[]
): string {
  const subs = getVisibleSubcommands(cmd);
  const subNames = subs.flatMap(c => [c.name(), ...c.aliases()]).join(' ');
  const opts = getVisibleOptions(cmd);
  const optSpecs = opts.map(o => `\\\n    ${formatOptionSpec(o)} `).join('');

  const caseBranches = subs
    .map(sub => {
      const subFnName = `${fnName}_${sub.name().replace(/-/g, '_')}`;
      const subSubs = getVisibleSubcommands(sub);
      if (subSubs.length > 0) {
        generateBranchHandler(sub, subFnName, leafFunctions);
      } else {
        const leaf = generateLeafHandler(sub, subFnName);
        if (leaf) leafFunctions.push(leaf);
      }
      const hasContent =
        subSubs.length > 0 ||
        getVisibleOptions(sub).length > 0 ||
        getRegisteredArguments(sub).length > 0;
      const body = hasContent ? subFnName : '_normal';
      const matchPattern = [sub.name(), ...sub.aliases()].join('|');
      return `    ${matchPattern}) ${body} ;;`;
    })
    .join('\n');

  const fn = `${fnName}() {
  local state line
  typeset -A opt_args

  _arguments -C ${optSpecs}\\
    '1:subcommand:(${subNames})' \\
    '*:: :->args'

  case $state in
    args)
      case $line[1] in
${caseBranches}
      esac
      ;;
  esac
}
`;
  leafFunctions.push(fn);
  return fn;
}

export function generateZshCompletion(program: Command): string {
  const leafFunctions: string[] = [];
  const mainFnName = `_${CLI_NAME}`;

  generateBranchHandler(program, mainFnName, leafFunctions);

  return `# Zsh completion for ${CLI_NAME}. Generated by "${CLI_NAME} completion zsh".
# Install: source <(./src/cli/bin/cli completion zsh)

${leafFunctions.join('\n')}
compdef ${mainFnName} ${CLI_NAME} ./src/cli/bin/cli
`;
}

export function createCompletionCommand(program: Command): Command {
  const completion = new Command('completion').description(
    'Generate shell completion script'
  );

  completion
    .command('zsh')
    .description(
      'Generate Zsh completion script (writes src/cli/_completion.zsh and prints to stdout)'
    )
    .action(async () => {
      const content = generateZshCompletion(program);
      const here = dirname(fileURLToPath(import.meta.url));
      const outputPath = resolve(here, '..', '_completion.zsh');
      await writeFile(outputPath, content, 'utf-8');
      process.stdout.write(content);
      process.stderr.write(`\n# wrote ${outputPath}\n`);
    });

  return completion;
}
