// Auto-generated by scripts/db/generate-schema-review.ts
// Do not edit manually — re-run to regenerate.
/* eslint-disable */
export {};

// ── Column type flags ──
type Text = 'Text';
type Real = 'Real';
type Timestamp = 'Timestamp';
type Bool = 'Bool';

// ── Column modifier flags ──
type PK = { _pk: true };
type DEFAULT<V> = { _default: V };

// ── OnDelete flags ──
namespace ON_DELETE {
  export type CASCADE = { _onDelete: 'cascade' };
  export type SET_NULL = { _onDelete: 'set null' };
  export type SET_DEFAULT = { _onDelete: 'set default' };
  export type RESTRICT = { _onDelete: 'restrict' };
  export type NO_ACTION = { _onDelete: 'no action' };
}

// ── Index flags ──
type UNIQUE = { _unique: true };
type PARTIAL_IDX = { _partial: true };

type JobListSource = {
  // ── base ──
  id: Text | PK;
  createdAt: Timestamp | DEFAULT<"strftime('%Y-%m-%dT%H:%M:%fZ', 'now')">;
  updatedAt: Timestamp | DEFAULT<"strftime('%Y-%m-%dT%H:%M:%fZ', 'now')">;
  // ── fields ──
  isActive: Bool | DEFAULT<1>;
  isProcessed: Bool | DEFAULT<0>;
  url: Text;
  divisions?: Text;
  locations?: Text;
  parserScript?: Text;
  // ── relations ──
  ofJobSourceId: Text | ON_DELETE.CASCADE | JobSource['id'];
  // ── indexes ──
  _indexes: {
    isActive: [JobListSource['isActive']];
    ofJobSourceId: [JobListSource['ofJobSourceId']];
    url: [JobListSource['url']] | UNIQUE;
  };
};

type JobPost = {
  // ── base ──
  id: Text | PK;
  createdAt: Timestamp | DEFAULT<"strftime('%Y-%m-%dT%H:%M:%fZ', 'now')">;
  updatedAt: Timestamp | DEFAULT<"strftime('%Y-%m-%dT%H:%M:%fZ', 'now')">;
  // ── fields ──
  isProcessed: Bool | DEFAULT<0>;
  title: Text;
  url: Text;
  company?: Text;
  description?: Text;
  isRemote?: Bool;
  jobType?: Text;
  location?: Text;
  postedAt?: Timestamp;
  salaryCurrency?: Text;
  salaryInterval?: Text;
  salaryMax?: Real;
  salaryMin?: Real;
  summary?: Text;
  // ── relations ──
  ofJobSourceId: Text | ON_DELETE.CASCADE | JobSource['id'];
  ofJobListSourceId?: Text | ON_DELETE.SET_NULL | JobListSource['id'];
  // ── indexes ──
  _indexes: {
    createdAt: [JobPost['createdAt']];
    postedAt: [JobPost['postedAt']];
    ofJobListSourceId: [JobPost['ofJobListSourceId']];
    ofJobSourceId: [JobPost['ofJobSourceId']];
    url: [JobPost['url']] | UNIQUE;
  };
};

type JobPostEval = {
  // ── base ──
  id: Text | PK;
  createdAt: Timestamp | DEFAULT<"strftime('%Y-%m-%dT%H:%M:%fZ', 'now')">;
  updatedAt: Timestamp | DEFAULT<"strftime('%Y-%m-%dT%H:%M:%fZ', 'now')">;
  // ── fields ──
  interestScore?: Real;
  interestScoreReason?: Text;
  skillScore?: Real;
  skillScoreBreakdown?: Text;
  skillScoreReason?: Text;
  titleRelavency?: Real;
  titleRelavencyReason?: Text;
  // ── relations ──
  ofJobPostId: Text | ON_DELETE.CASCADE | JobPost['id'];
  // ── indexes ──
  _indexes: {
    titleRelavency: [JobPostEval['titleRelavency']];
    ofJobPostId: [JobPostEval['ofJobPostId']] | UNIQUE;
  };
};

type JobSource = {
  // ── base ──
  id: Text | PK;
  createdAt: Timestamp | DEFAULT<"strftime('%Y-%m-%dT%H:%M:%fZ', 'now')">;
  updatedAt: Timestamp | DEFAULT<"strftime('%Y-%m-%dT%H:%M:%fZ', 'now')">;
  // ── fields ──
  isActive: Bool | DEFAULT<1>;
  isProcessed: Bool | DEFAULT<0>;
  name: Text;
  url: Text;
  // ── indexes ──
  _indexes: {
    isActive: [JobSource['isActive']];
    url: [JobSource['url']] | UNIQUE;
  };
};

type PipelineState = {
  // ── base ──
  id: Text | PK;
  createdAt: Timestamp | DEFAULT<"strftime('%Y-%m-%dT%H:%M:%fZ', 'now')">;
  updatedAt: Timestamp | DEFAULT<"strftime('%Y-%m-%dT%H:%M:%fZ', 'now')">;
  // ── fields ──
  state: Text;
  task: Text;
  reason?: Text;
  // ── relations ──
  ofJobListSourceId?: Text | ON_DELETE.CASCADE | JobListSource['id'];
  ofJobPostId?: Text | ON_DELETE.CASCADE | JobPost['id'];
  ofJobSourceId?: Text | ON_DELETE.CASCADE | JobSource['id'];
  ofSourceSeedId?: Text | ON_DELETE.CASCADE | SourceSeed['id'];
  // ── indexes ──
  _indexes: {
    ofJobPostId: [PipelineState['ofJobPostId']];
    ofJobListSourceId: [PipelineState['ofJobListSourceId']];
    ofJobSourceId: [PipelineState['ofJobSourceId']];
    ofSourceSeedId: [PipelineState['ofSourceSeedId']];
    state: [PipelineState['state']];
    task: [PipelineState['task']];
  };
};

type SourceSeed = {
  // ── base ──
  id: Text | PK;
  createdAt: Timestamp | DEFAULT<"strftime('%Y-%m-%dT%H:%M:%fZ', 'now')">;
  updatedAt: Timestamp | DEFAULT<"strftime('%Y-%m-%dT%H:%M:%fZ', 'now')">;
  // ── fields ──
  isProcessed: Bool | DEFAULT<0>;
  name: Text;
  title: Text;
  url: Text;
  // ── indexes ──
  _indexes: {
    url: [SourceSeed['url']] | UNIQUE;
  };
};
