// Auto-generated by scripts/db/generate-schema-review.ts
// Do not edit manually — re-run to regenerate.
/* eslint-disable */
export {}

// ── Column type flags ──
type Integer = 'Integer'
type Text = 'Text'

// ── Column modifier flags ──
type PK = { _pk: true }
type Default<V> = { _default: V }

// ── OnDelete flags ──
namespace OnDelete {
  export type CASCADE = { _onDelete: 'cascade' }
  export type SET_NULL = { _onDelete: 'set null' }
  export type SET_DEFAULT = { _onDelete: 'set default' }
  export type RESTRICT = { _onDelete: 'restrict' }
  export type NO_ACTION = { _onDelete: 'no action' }
}

// ── Index flags ──
type Unique = { _unique: true }
type PartialIdx = { _partial: true }

type Job = {
  // ── base ──
  id?: Integer | PK
  createdAt: Text | Default<'CURRENT_TIMESTAMP'>
  // ── fields ──
  company: Text
  title: Text
  location?: Text
  url?: Text
}
